stages:
  - build
  - test
  - deploy
  - migration
  - seed

build-dependence:
  stage: build
  script:
    - echo $CI_PROJECT_DIR
    - rm -rf ./vendor
    - rm -rf composer.lock
    - composer install
    - composer update
  cache:
    paths:
      - ./vendor
    key: ${CI_COMMIT_REF_SLUG}
    policy: push
  only:
    refs:
      - develop
      - staging
      - master
    changes:
      - composer.json
  artifacts:
    expire_in: 1 hour
    paths:
      - vendor/
  tags:
    - DEV_SHELL


# test-convention:
#   stage: test
#   script:
#     - echo $CI_PROJECT_DIR
#     - php vendor/bin/phpcs --standard=phpcs-laravel app/
#   cache:
#     paths:
#       - ./vendor
#     key: ${CI_COMMIT_REF_SLUG}
#     policy: pull
#   only:
#     refs:
#       - develop
#       - staging
#       - master
#   tags:
#     - DEV_SHELL

include:
  - local: .gitlab/dev.gitlab-ci.yml
  # - local: .gitlab/stg.gitlab-ci.yml
  # - local: .gitlab/master.gitlab-ci.yml
