deploy-develop:
  stage: deploy
  script:
    # - mkdir -p storage/app/public/firebase
    # - cat "$CI_DEV_FIREBASE" > "storage/app/public/firebase/firebase_credentials-g71en-173da651a0.json"
    - cat "$DEV_ENV_FILE" > ".env"
    - composer install
    - rsync --delete -hrzav --exclude='storage' $CI_PROJECT_DIR/ $CI_DEV_SSH_USER@$CI_DEV_ADMIN_IP:/srv/WeddingOnline-api/
    - ssh $CI_DEV_SSH_USER@$CI_DEV_ADMIN_IP "sudo find /srv/WeddingOnline-api/ -type d -exec chmod 775 {} \; && sudo find /srv/WeddingOnline-api/ -type f -exec chmod 664 {} \;"
    - ssh $CI_DEV_SSH_USER@$CI_DEV_ADMIN_IP "cd /srv/WeddingOnline-api/ && php artisan cache:clear"
    - ssh $CI_DEV_SSH_USER@$CI_DEV_ADMIN_IP "cd /srv/WeddingOnline-api/ && php artisan config:clear"
    - ssh $CI_DEV_SSH_USER@$CI_DEV_ADMIN_IP "cd /srv/WeddingOnline-api/ && php artisan key:generate"
  cache:
    paths:
      - ./vendor
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
  only:
    - develop
  tags:
    - DEV_SHELL
migrate-develop:
  stage: migration
  script:
    - ssh $CI_DEV_SSH_USER@$CI_DEV_ADMIN_IP "cd /srv/WeddingOnline-api/ && yes | php artisan migrate"
  when: manual
  only:
    - develop
  tags:
    - DEV_SHELL
seed-develop:
  stage: seed
  script:
    - ssh $CI_DEV_SSH_USER@$CI_DEV_ADMIN_IP "cd /srv/WeddingOnline-api/ && yes | php artisan db:seed"
  when: manual
  only:
    - develop
  tags:
    - DEV_SHELL
rollback-db-develop:
  stage: seed
  script:
    - ssh $CI_DEV_SSH_USER@$CI_DEV_ADMIN_IP "cd /srv/WeddingOnline-api/ && yes | php artisan migrate:rollback"
  when: manual
  only:
    - develop
  tags:
    - DEV_SHELL
