deploy-staging:
  stage: deploy
  script:
    - cat "$STG_ENV_FILE" > ".env"
    - composer install
    - rsync --delete -hrzav --exclude='storage' $CI_PROJECT_DIR/ $CI_STG_SSH_USER@$CI_STG_ADMIN_IP:/srv/WeddingOnline-api/
    - ssh $CI_STG_SSH_USER@$CI_STG_ADMIN_IP "sudo find /srv/WeddingOnline-api/ -type d -exec chmod 775 {} \; && sudo find /srv/WeddingOnline-api/ -type f -exec chmod 664 {} \;"
    - ssh $CI_STG_SSH_USER@$CI_STG_ADMIN_IP "cd /srv/WeddingOnline-api/ && php artisan cache:clear"
    - ssh $CI_STG_SSH_USER@$CI_STG_ADMIN_IP "cd /srv/WeddingOnline-api/ && php artisan config:clear"
    - ssh $CI_STG_SSH_USER@$CI_STG_ADMIN_IP "cd /srv/WeddingOnline-api/ && php artisan key:generate"

  cache:
    paths:
      - ./vendor
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
  only:
    - staging
  tags:
    - DEV_SHELL
migrate-staging:
  stage: migration
  script:
    - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $CI_STG_SSH_USER@$CI_STG_ADMIN_IP "cd /srv/WeddingOnline-api/ && yes | php artisan migrate"
  when: manual
  only:
    - staging
  tags:
    - DEV_SHELL
seed-staging:
  stage: seed
  script:
    - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $CI_STG_SSH_USER@$CI_STG_ADMIN_IP "cd /srv/WeddingOnline-api/ && yes | php artisan db:seed"
  when: manual
  only:
    - staging
  tags:
    - DEV_SHELL
rollback-db-staging:
  stage: seed
  script:
    - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $CI_STG_SSH_USER@$CI_STG_ADMIN_IP "cd /srv/WeddingOnline-api/ && yes | php artisan migrate:rollback"
  when: manual
  only:
    - staging
  tags:
    - DEV_SHELL
