deploy-staging:
  stage: deploy
  script:
    - cat "$STG_ENV_FILE" > ".env"
    - mkdir -p storage/app/public/firebase
    - cat "$CI_STG_FIREBASE" > "storage/app/public/firebase/firebase_credentials-g71en-173da651a0.json"
    - rsync --delete -hrz --delete -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" $CI_PROJECT_DIR/ centos@10.0.1.213:/srv/WeddingOnline-api
    - rsync --delete -hrz --delete -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" $CI_PROJECT_DIR/ centos@10.0.1.96:/srv/WeddingOnline-api
    - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null centos@10.0.1.213 "cd /srv/WeddingOnline-api/ && php artisan cache:clear"
    - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null centos@10.0.1.96 "cd /srv/WeddingOnline-api/ && php artisan cache:clear"
    - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null centos@10.0.1.213 "cd /srv/WeddingOnline-api/ && php artisan config:clear"
    - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null centos@10.0.1.96 "cd /srv/WeddingOnline-api/ && php artisan config:clear"

  cache:
    paths:
      - ./vendor
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
  only:
    - staging
  tags:
    - DEV_SHELL
migrate-staging:
  stage: migration
  script:
    - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null centos@10.0.1.213 "cd /srv/WeddingOnline-api/ && yes | php artisan migrate"
  when: manual
  only:
    - staging
  tags:
    - DEV_SHELL
seed-staging:
  stage: seed
  script:
    - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null centos@10.0.1.213 "cd /srv/WeddingOnline-api/ && yes | php artisan db:seed"
  when: manual
  only:
    - staging
  tags:
    - DEV_SHELL
